tinyproxy:
  image: b79ce5b117d8
  container_name: tinyproxy
  ports:
    - 8123:8888
  command: ANY
  environment:
    - BASIC_AUTH_USER=${BASIC_AUTH_USER}
    - BASIC_AUTH_PASSWORD=${BASIC_AUTH_PASSWORD}
  restart: unless-stopped

ss5:
  image: dijedodol/simple-socks5-server:latest
  container_name: ss5
  ports:
    - 8080:1080
  environment:
    - SSS_USERNAME=${SSS_USERNAME}
    - SSS_PASSWORD=${SSS_PASSWORD}
  restart: unless-stopped

telegram-proxy:
  image: telegrammessenger/proxy:latest
  container_name: tg-proxy
  ports:
    - 443:443 
  volumes:
    - proxy-config:/data
  restart: unless-stopped

