tinyproxy:
  image: 2ddc7e3ab1da
  container_name: tinyproxy
  ports:
    - 8123:8888
  command: ANY
  environment:
    - BASIC_AUTH_USER=${HTTP_USER}
    - BASIC_AUTH_PASSWORD=${HTTP_PASSWORD}
  restart: unless-stopped

ss5:
  image: dijedodol/simple-socks5-server:latest
  container_name: ss5
  ports:
    - 8080:1080
  environment:
    - SSS_USERNAME=${SOCKS5_USER}
    - SSS_PASSWORD=${SOCKS5_PASSWORD}
  restart: unless-stopped

telegram-proxy:
  image: telegrammessenger/proxy:latest
  container_name: tg-proxy
  ports:
    - 443:443 
  volumes:
    - proxy-config:/data
  restart: unless-stopped

